# Project Name
TARGET = murmur

# Sources
CPP_SOURCES = MurmurBoids.cpp \
              audio/circular_buffer.cpp \
              audio/grain_voice.cpp \
              audio/grain_pool.cpp \
              boids/boids.cpp \
              boids/scheduler.cpp \
              ui/display.cpp \
              ui/led_grid.cpp

# Library Locations
LIBDAISY_DIR = ../libDaisy
DAISYSP_DIR = ../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
